
# 保护配置
protect-config:
  # 配置文件必须包含 default 节点，请勿删除！！！
  default:
    # 禁止玩家修改世界（放置方块，填充水、岩浆，放置画，修改物品展示框和花盆...）
    anti-world-edit: false
    # 禁止玩家 pvp (玩家互相伤害)
    anti-pvp: false
    # 禁止玩家进入世界 (PlayerChangedWorldEvent)
    anti-player-enter: false
    # 使爆炸在该世界不破坏方块 (EntityExplodeEvent)
    anti-explosion: false
    # 禁止玩家与该世界的方块交互 (PlayerInteractEvent)
    anti-block-interaction: false
    # 禁止玩家攻击该世界的实体 (不包含玩家互相伤害)
    anti-attack-entity: false
    # 禁止玩家与实体交互 (onPlayerInteractEntity)
    anti-entity-interaction: false

    # 玩家无权限时 actionbar 显示的消息 (MiniMessage 格式)
    # 已做频繁触发优化，1s 内只会发送一次
    message:
      anti-world-edit: "<color:#d60032><b>[WP]</b></color> <red>你没有权限修改这个世界.</red>"
      anti-pvp: "<color:#d60032><b>[WP]</b></color> <red>已禁止在该世界 PVP.</red>"
      anti-player-enter: "<color:#d60032><b>[WP]</b></color> <red>你没有权限进入这个世界.</red>"
      anti-block-interaction: "<color:#d60032><b>[WP]</b></color> <red>你没有权限与这个世界交互.</red>"
      anti-attack-entity: "<color:#d60032><b>[WP]</b></color> <red>已禁止攻击此世界的生物.</red>"
      anti-entity-interaction: "<color:#d60032><b>[WP]</b></color> <red>已禁止与此世界的生物交互.</red>"
  common:
    # 在 parent 的基础上覆写配置
    # 若没有填写 parent，默认以 default 为 parent
    # parent: default
    anti-world-edit: true
    anti-explosion: true

    message:
      anti-world-edit: "<color:#d60032><b>[WP]</b></color> <red>你没有此世界的居住权.</red>"
  
  hub-config:
    parent: common
    anti-block-interaction: true
    anti-attack-entity: true

    message:
      anti-world-edit: "<color:#d60032><b>[WP]</b></color> <red>你不能修改主城.</red>"


# 指定哪些世界使用哪些保护配置
# 未指定的默认使用 default 配置
# 指定 disable 则为在该世界禁用所有保护
world-config:
  "world": common
  "hub": hub-config
  "world_the_end": disable

# 主命令
# /wp status 查看保护设置总览
# /wp status <world> 查看某个世界的保护设置
# /wp reload 重载配置文件
# /wp version 显示插件版本

# 权限列表:
# wp.admin: 使用 /wp 命令
# 使玩家绕过某个保护:
# wp.bypass.<world>.anti-world-edit
# wp.bypass.<world>.anti-pvp
# wp.bypass.<world>.anti-player-enter
# wp.bypass.<world>.anti-block-interaction
# wp.bypass.<world>.anti-attack-entity
# wp.bypass.<world>.anti-entity-interaction